// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVhTy1OCH0vgILfZWC54Tfay_JxH8VcE',
    appId: '1:267998066997:web:4d3a51078a64d2fdda347c',
    messagingSenderId: '267998066997',
    projectId: 'kv-app-a7727',
    authDomain: 'kv-app-a7727.firebaseapp.com',
    storageBucket: 'kv-app-a7727.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FP8FT7qSQbDAWZiNEghkRI0VUxrXkR8',
    appId: '1:267998066997:android:a42e3c731de6dafbda347c',
    messagingSenderId: '267998066997',
    projectId: 'kv-app-a7727',
    storageBucket: 'kv-app-a7727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9z0gU2-d5SCssvIn8I86noMEgNOz8j0',
    appId: '1:267998066997:ios:5102847b2069e7d6da347c',
    messagingSenderId: '267998066997',
    projectId: 'kv-app-a7727',
    storageBucket: 'kv-app-a7727.firebasestorage.app',
    iosBundleId: 'com.example.myReelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9z0gU2-d5SCssvIn8I86noMEgNOz8j0',
    appId: '1:267998066997:ios:5102847b2069e7d6da347c',
    messagingSenderId: '267998066997',
    projectId: 'kv-app-a7727',
    storageBucket: 'kv-app-a7727.firebasestorage.app',
    iosBundleId: 'com.example.myReelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFVhTy1OCH0vgILfZWC54Tfay_JxH8VcE',
    appId: '1:267998066997:web:d6b618ecd9034b0eda347c',
    messagingSenderId: '267998066997',
    projectId: 'kv-app-a7727',
    authDomain: 'kv-app-a7727.firebaseapp.com',
    storageBucket: 'kv-app-a7727.firebasestorage.app',
  );

}